services:
  onlyoffice-docs:
    image: onlyoffice/documentserver:latest
    restart: always
    ports:
      - "8080:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - JWT_ENABLED=true
      - JWT_SECRET=my_super_secret_key
      - JWT_HEADER=Authorization
      - ALLOW_PRIVATE_ADDRESS=true
      - MACRO_ENABLE=true
    volumes:
      - ./onlyoffice/data:/var/www/onlyoffice/Data
      - ./onlyoffice/logs:/var/log/onlyoffice
      - ./onlyoffice/lib:/var/lib/onlyoffice
      - ./onlyoffice/db:/var/lib/postgresql

networks:
  default:
    name: nextjs-network
