-- Migration: Replace status flow after VALIDATED
-- Old: VALIDATED → PENDING_SUBMISSION → SUBMITTED → PROCESSED
-- New: VALIDATED → SUBMITTED_TO_HIGHER_OFFICE → PROCESSED_BY_HIGHER_OFFICE

-- Convert PENDING_SUBMISSION → VALIDATED (user already validated, awaiting user submit to higher offices)
UPDATE submissions SET status = 'VALIDATED' WHERE status = 'PENDING_SUBMISSION';

-- Convert SUBMITTED → SUBMITTED_TO_HIGHER_OFFICE
UPDATE submissions SET status = 'SUBMITTED_TO_HIGHER_OFFICE' WHERE status = 'SUBMITTED';

-- Convert PROCESSED → PROCESSED_BY_HIGHER_OFFICE
UPDATE submissions SET status = 'PROCESSED_BY_HIGHER_OFFICE' WHERE status = 'PROCESSED';