


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



-- ============================================
-- STORAGE BUCKETS
-- ============================================
-- See supabase/migrations/20260331212928_storage.sql for full storage schema dump
-- ============================================

-- Create storage buckets
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types) VALUES
  ('signatures', 'signatures', false, NULL, NULL),
  ('pdfs', 'pdfs', false, NULL, NULL),
  ('submissions-pdf', 'submissions-pdf', true, 52428800, ARRAY['application/pdf']),
  ('submissions-docx', 'submissions-docx', true, 52428800, ARRAY['application/vnd.openxmlformats-officedocument.wordprocessingml.document']),
  ('drafts-pdf', 'drafts-pdf', false, NULL, NULL),
  ('drafts-docx', 'drafts-docx', false, NULL, NULL)
ON CONFLICT (id) DO NOTHING;

GRANT ALL ON storage.objects TO "anon";
GRANT ALL ON storage.objects TO "authenticated";
GRANT ALL ON storage.objects TO "service_role";

-- ============================================


CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE TYPE "public"."publication_types" AS ENUM (
    'JOURNAL',
    'BOOK'
);


ALTER TYPE "public"."publication_types" OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."handle_new_user"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    AS $$begin
  insert into public.users (id, email, role)
  values (new.id, new.email, 'admin');
  return new;
end;$$;


ALTER FUNCTION "public"."handle_new_user"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."awards" (
    "award_id" integer NOT NULL,
    "title" character varying(200) NOT NULL,
    "description" "text"
);


ALTER TABLE "public"."awards" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."awards_award_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."awards_award_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."awards_award_id_seq" OWNED BY "public"."awards"."award_id";



CREATE TABLE IF NOT EXISTS "public"."departments" (
    "department_id" integer NOT NULL,
    "name" character varying(100) NOT NULL,
    "description" "text"
);


ALTER TABLE "public"."departments" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."departments_department_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."departments_department_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."departments_department_id_seq" OWNED BY "public"."departments"."department_id";



CREATE TABLE IF NOT EXISTS "public"."publication_authors" (
    "publication_id" integer NOT NULL,
    "user_id" "uuid" NOT NULL,
    "author_rank" integer
);


ALTER TABLE "public"."publication_authors" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."publication_award_applications" (
    "id" integer NOT NULL,
    "publication_id" integer NOT NULL,
    "award_id" integer NOT NULL,
    "submission_id" integer,
    "application_date" "date" DEFAULT CURRENT_DATE
);


ALTER TABLE "public"."publication_award_applications" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."publication_award_applications_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."publication_award_applications_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."publication_award_applications_id_seq" OWNED BY "public"."publication_award_applications"."id";



CREATE TABLE IF NOT EXISTS "public"."publication_per_award" (
    "id" bigint NOT NULL,
    "award_id" integer NOT NULL,
    "publication_type_id" bigint NOT NULL
);


ALTER TABLE "public"."publication_per_award" OWNER TO "postgres";


ALTER TABLE "public"."publication_per_award" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."publication_per_award_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."publication_type" (
    "id" bigint NOT NULL,
    "name" character varying NOT NULL
);


ALTER TABLE "public"."publication_type" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."publications" (
    "publication_id" integer NOT NULL,
    "type" character varying(50),
    "title" character varying(255) NOT NULL,
    "publisher" character varying(255),
    "publication_status" character varying(50),
    "date_published" "date",
    "issue_number" character varying(50),
    "page_numbers" character varying(50),
    "volume_number" character varying(50),
    "journal_name" "text",
    "doi" "text",
    "publication_type_id" bigint
);


ALTER TABLE "public"."publications" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."publications_publication_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."publications_publication_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."publications_publication_id_seq" OWNED BY "public"."publications"."publication_id";



CREATE TABLE IF NOT EXISTS "public"."submissions" (
    "submission_id" integer NOT NULL,
    "submitter_id" "uuid" NOT NULL,
    "award_id" integer,
    "publication_id" integer,
    "reviewed_by_admin_id" "uuid",
    "date_submitted" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    "status" character varying(20) DEFAULT 'pending'::character varying,
    "remarks" "text",
    "pdf_json_data" "jsonb" DEFAULT '{}'::"jsonb" NOT NULL,
    "logs" "jsonb" DEFAULT '[]'::"jsonb",
    "form41_path" character varying(500),
    "form42_path" character varying(500),
    "form43_path" character varying(500),
    "form44_path" character varying(500)
);


ALTER TABLE "public"."submissions" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."submissions_submission_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."submissions_submission_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."submissions_submission_id_seq" OWNED BY "public"."submissions"."submission_id";



ALTER TABLE "public"."publication_type" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."types_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."users" (
    "id" "uuid" NOT NULL,
    "role" "text" DEFAULT 'nonteaching'::"text" NOT NULL,
    "created_at" timestamp without time zone DEFAULT "now"(),
    "email" "text" NOT NULL,
    "first_name" "text",
    "middle_name" "text",
    "last_name" "text",
    "signature_path" "text",
    "university" character varying,
    "college" character varying,
    "department" character varying,
    "contact_number" character varying,
    "position" character varying,
    "email_address" character varying,
    CONSTRAINT "profiles_role_check" CHECK (("role" = ANY (ARRAY['teaching'::"text", 'nonteaching'::"text", 'admin'::"text"])))
);


ALTER TABLE "public"."users" OWNER TO "postgres";


COMMENT ON COLUMN "public"."users"."signature_path" IS 'Image of signature of user';



ALTER TABLE ONLY "public"."awards" ALTER COLUMN "award_id" SET DEFAULT "nextval"('"public"."awards_award_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."departments" ALTER COLUMN "department_id" SET DEFAULT "nextval"('"public"."departments_department_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."publication_award_applications" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."publication_award_applications_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."publications" ALTER COLUMN "publication_id" SET DEFAULT "nextval"('"public"."publications_publication_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."submissions" ALTER COLUMN "submission_id" SET DEFAULT "nextval"('"public"."submissions_submission_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."awards"
    ADD CONSTRAINT "awards_pkey" PRIMARY KEY ("award_id");



ALTER TABLE ONLY "public"."departments"
    ADD CONSTRAINT "departments_pkey" PRIMARY KEY ("department_id");



ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "profiles_email_key" UNIQUE ("email");



ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "profiles_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."publication_authors"
    ADD CONSTRAINT "publication_authors_pkey" PRIMARY KEY ("publication_id", "user_id");



ALTER TABLE ONLY "public"."publication_award_applications"
    ADD CONSTRAINT "publication_award_applications_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."publication_award_applications"
    ADD CONSTRAINT "publication_award_applications_publication_id_award_id_key" UNIQUE ("publication_id", "award_id");



ALTER TABLE ONLY "public"."publications"
    ADD CONSTRAINT "publications_pkey" PRIMARY KEY ("publication_id");



ALTER TABLE ONLY "public"."submissions"
    ADD CONSTRAINT "submissions_pkey" PRIMARY KEY ("submission_id");



ALTER TABLE ONLY "public"."publication_type"
    ADD CONSTRAINT "types_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "profiles_id_fkey" FOREIGN KEY ("id") REFERENCES "auth"."users"("id");



ALTER TABLE ONLY "public"."publication_authors"
    ADD CONSTRAINT "publication_authors_publication_id_fkey" FOREIGN KEY ("publication_id") REFERENCES "public"."publications"("publication_id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."publication_authors"
    ADD CONSTRAINT "publication_authors_user_id_fkey1" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id");



ALTER TABLE ONLY "public"."publication_award_applications"
    ADD CONSTRAINT "publication_award_applications_award_id_fkey" FOREIGN KEY ("award_id") REFERENCES "public"."awards"("award_id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."publication_award_applications"
    ADD CONSTRAINT "publication_award_applications_publication_id_fkey" FOREIGN KEY ("publication_id") REFERENCES "public"."publications"("publication_id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."publication_award_applications"
    ADD CONSTRAINT "publication_award_applications_submission_id_fkey" FOREIGN KEY ("submission_id") REFERENCES "public"."submissions"("submission_id");



ALTER TABLE ONLY "public"."publication_per_award"
    ADD CONSTRAINT "publication_per_award_award_id_fkey" FOREIGN KEY ("award_id") REFERENCES "public"."awards"("award_id");



ALTER TABLE ONLY "public"."publication_per_award"
    ADD CONSTRAINT "publication_per_award_publication_type_id_fkey" FOREIGN KEY ("publication_type_id") REFERENCES "public"."publication_type"("id");



ALTER TABLE ONLY "public"."publications"
    ADD CONSTRAINT "publications_publication_type_id_fkey" FOREIGN KEY ("publication_type_id") REFERENCES "public"."publication_type"("id");



ALTER TABLE ONLY "public"."submissions"
    ADD CONSTRAINT "submissions_award_id_fkey" FOREIGN KEY ("award_id") REFERENCES "public"."awards"("award_id");



ALTER TABLE ONLY "public"."submissions"
    ADD CONSTRAINT "submissions_publication_id_fkey" FOREIGN KEY ("publication_id") REFERENCES "public"."publications"("publication_id");



ALTER TABLE ONLY "public"."submissions"
    ADD CONSTRAINT "submissions_reviewed_by_admin_id_fkey" FOREIGN KEY ("reviewed_by_admin_id") REFERENCES "public"."users"("id") ON UPDATE CASCADE;



ALTER TABLE ONLY "public"."submissions"
    ADD CONSTRAINT "submissions_submitter_id_fkey" FOREIGN KEY ("submitter_id") REFERENCES "public"."users"("id");



ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "users_email_address_fkey" FOREIGN KEY ("email_address") REFERENCES "public"."users"("email");



CREATE POLICY "Public profiles are viewable by everyone." ON "public"."users" FOR SELECT USING (true);



CREATE POLICY "Users can insert own profile" ON "public"."users" FOR INSERT WITH CHECK (("auth"."uid"() = "id"));



CREATE POLICY "Users can insert their own profile." ON "public"."users" FOR INSERT WITH CHECK ((( SELECT "auth"."uid"() AS "uid") = "id"));



CREATE POLICY "Users can update own profile." ON "public"."users" FOR UPDATE USING ((( SELECT "auth"."uid"() AS "uid") = "id"));





ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";

























































































































































GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "anon";
GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "service_role";


















GRANT ALL ON TABLE "public"."awards" TO "anon";
GRANT ALL ON TABLE "public"."awards" TO "authenticated";
GRANT ALL ON TABLE "public"."awards" TO "service_role";



GRANT ALL ON SEQUENCE "public"."awards_award_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."awards_award_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."awards_award_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."departments" TO "anon";
GRANT ALL ON TABLE "public"."departments" TO "authenticated";
GRANT ALL ON TABLE "public"."departments" TO "service_role";



GRANT ALL ON SEQUENCE "public"."departments_department_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."departments_department_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."departments_department_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."publication_authors" TO "anon";
GRANT ALL ON TABLE "public"."publication_authors" TO "authenticated";
GRANT ALL ON TABLE "public"."publication_authors" TO "service_role";



GRANT ALL ON TABLE "public"."publication_award_applications" TO "anon";
GRANT ALL ON TABLE "public"."publication_award_applications" TO "authenticated";
GRANT ALL ON TABLE "public"."publication_award_applications" TO "service_role";



GRANT ALL ON SEQUENCE "public"."publication_award_applications_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."publication_award_applications_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."publication_award_applications_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."publication_per_award" TO "anon";
GRANT ALL ON TABLE "public"."publication_per_award" TO "authenticated";
GRANT ALL ON TABLE "public"."publication_per_award" TO "service_role";



GRANT ALL ON SEQUENCE "public"."publication_per_award_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."publication_per_award_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."publication_per_award_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."publication_type" TO "anon";
GRANT ALL ON TABLE "public"."publication_type" TO "authenticated";
GRANT ALL ON TABLE "public"."publication_type" TO "service_role";



GRANT ALL ON TABLE "public"."publications" TO "anon";
GRANT ALL ON TABLE "public"."publications" TO "authenticated";
GRANT ALL ON TABLE "public"."publications" TO "service_role";



GRANT ALL ON SEQUENCE "public"."publications_publication_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."publications_publication_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."publications_publication_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."submissions" TO "anon";
GRANT ALL ON TABLE "public"."submissions" TO "authenticated";
GRANT ALL ON TABLE "public"."submissions" TO "service_role";



GRANT ALL ON SEQUENCE "public"."submissions_submission_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."submissions_submission_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."submissions_submission_id_seq" TO "service_role";



GRANT ALL ON SEQUENCE "public"."types_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."types_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."types_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."users" TO "anon";
GRANT ALL ON TABLE "public"."users" TO "authenticated";
GRANT ALL ON TABLE "public"."users" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";































